version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/nshekhawat/rate-limiter-go

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - unconvert
    - gocritic
    - revive
    - gosec
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
      exclude-functions:
        - (*go.uber.org/zap.Logger).Sync
        - (io.Closer).Close
        - (*github.com/redis/go-redis/v9.Client).Close
        - fmt.Sscanf
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
    gosec:
      excludes:
        - G104
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - gocritic
          - errcheck
      - path: \.pb\.go
        linters:
          - all

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
