// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/proto/ratelimiter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the rate limit (e.g., IP address, API key, user ID)
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Resource being accessed (e.g., endpoint path, API method)
	Resource string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Number of tokens to consume (default: 1)
	Tokens        int64 `protobuf:"varint,3,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_api_proto_ratelimiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimiter_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *CheckRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *CheckRequest) GetTokens() int64 {
	if x != nil {
		return x.Tokens
	}
	return 0
}

type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the request is allowed
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// Maximum number of requests allowed in the window
	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Number of requests remaining in the current window
	Remaining int64 `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// Seconds until the rate limit resets (only set if not allowed)
	RetryAfterSeconds int64 `protobuf:"varint,4,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	// Unix timestamp when the rate limit will reset
	ResetAtUnix   int64 `protobuf:"varint,5,opt,name=reset_at_unix,json=resetAtUnix,proto3" json:"reset_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_api_proto_ratelimiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimiter_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CheckResponse) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckResponse) GetRetryAfterSeconds() int64 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

func (x *CheckResponse) GetResetAtUnix() int64 {
	if x != nil {
		return x.ResetAtUnix
	}
	return 0
}

type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the rate limit
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Resource being accessed (optional, for resource-specific limits)
	Resource      string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_proto_ratelimiter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimiter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimiter_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *StatusRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of requests allowed in the window
	Limit int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Number of requests remaining in the current window
	Remaining int64 `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	// Unix timestamp when the rate limit will reset
	ResetAtUnix int64 `protobuf:"varint,3,opt,name=reset_at_unix,json=resetAtUnix,proto3" json:"reset_at_unix,omitempty"`
	// Current number of tokens available
	TokensAvailable float64 `protobuf:"fixed64,4,opt,name=tokens_available,json=tokensAvailable,proto3" json:"tokens_available,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_proto_ratelimiter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimiter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimiter_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *StatusResponse) GetRemaining() int64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *StatusResponse) GetResetAtUnix() int64 {
	if x != nil {
		return x.ResetAtUnix
	}
	return 0
}

func (x *StatusResponse) GetTokensAvailable() float64 {
	if x != nil {
		return x.TokensAvailable
	}
	return 0
}

type ResetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the rate limit to reset
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Resource to reset (optional, for resource-specific limits)
	Resource      string `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	mi := &file_api_proto_ratelimiter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimiter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimiter_proto_rawDescGZIP(), []int{4}
}

func (x *ResetRequest) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *ResetRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type ResetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the reset was successful
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Message describing the result
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetResponse) Reset() {
	*x = ResetResponse{}
	mi := &file_api_proto_ratelimiter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetResponse) ProtoMessage() {}

func (x *ResetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ratelimiter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetResponse.ProtoReflect.Descriptor instead.
func (*ResetResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ratelimiter_proto_rawDescGZIP(), []int{5}
}

func (x *ResetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_ratelimiter_proto protoreflect.FileDescriptor

const file_api_proto_ratelimiter_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/proto/ratelimiter.proto\x12\vratelimiter\"b\n" +
	"\fCheckRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\x12\x16\n" +
	"\x06tokens\x18\x03 \x01(\x03R\x06tokens\"\xb1\x01\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\x03R\tremaining\x12.\n" +
	"\x13retry_after_seconds\x18\x04 \x01(\x03R\x11retryAfterSeconds\x12\"\n" +
	"\rreset_at_unix\x18\x05 \x01(\x03R\vresetAtUnix\"K\n" +
	"\rStatusRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\"\x93\x01\n" +
	"\x0eStatusResponse\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x03R\tremaining\x12\"\n" +
	"\rreset_at_unix\x18\x03 \x01(\x03R\vresetAtUnix\x12)\n" +
	"\x10tokens_available\x18\x04 \x01(\x01R\x0ftokensAvailable\"J\n" +
	"\fResetRequest\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x1a\n" +
	"\bresource\x18\x02 \x01(\tR\bresource\"C\n" +
	"\rResetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xed\x01\n" +
	"\x12RateLimiterService\x12G\n" +
	"\x0eCheckRateLimit\x12\x19.ratelimiter.CheckRequest\x1a\x1a.ratelimiter.CheckResponse\x12I\n" +
	"\x0eGetLimitStatus\x12\x1a.ratelimiter.StatusRequest\x1a\x1b.ratelimiter.StatusResponse\x12C\n" +
	"\n" +
	"ResetLimit\x12\x19.ratelimiter.ResetRequest\x1a\x1a.ratelimiter.ResetResponseB1Z/github.com/nshekhawat/rate-limiter-go/api/protob\x06proto3"

var (
	file_api_proto_ratelimiter_proto_rawDescOnce sync.Once
	file_api_proto_ratelimiter_proto_rawDescData []byte
)

func file_api_proto_ratelimiter_proto_rawDescGZIP() []byte {
	file_api_proto_ratelimiter_proto_rawDescOnce.Do(func() {
		file_api_proto_ratelimiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ratelimiter_proto_rawDesc), len(file_api_proto_ratelimiter_proto_rawDesc)))
	})
	return file_api_proto_ratelimiter_proto_rawDescData
}

var file_api_proto_ratelimiter_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_ratelimiter_proto_goTypes = []any{
	(*CheckRequest)(nil),   // 0: ratelimiter.CheckRequest
	(*CheckResponse)(nil),  // 1: ratelimiter.CheckResponse
	(*StatusRequest)(nil),  // 2: ratelimiter.StatusRequest
	(*StatusResponse)(nil), // 3: ratelimiter.StatusResponse
	(*ResetRequest)(nil),   // 4: ratelimiter.ResetRequest
	(*ResetResponse)(nil),  // 5: ratelimiter.ResetResponse
}
var file_api_proto_ratelimiter_proto_depIdxs = []int32{
	0, // 0: ratelimiter.RateLimiterService.CheckRateLimit:input_type -> ratelimiter.CheckRequest
	2, // 1: ratelimiter.RateLimiterService.GetLimitStatus:input_type -> ratelimiter.StatusRequest
	4, // 2: ratelimiter.RateLimiterService.ResetLimit:input_type -> ratelimiter.ResetRequest
	1, // 3: ratelimiter.RateLimiterService.CheckRateLimit:output_type -> ratelimiter.CheckResponse
	3, // 4: ratelimiter.RateLimiterService.GetLimitStatus:output_type -> ratelimiter.StatusResponse
	5, // 5: ratelimiter.RateLimiterService.ResetLimit:output_type -> ratelimiter.ResetResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_ratelimiter_proto_init() }
func file_api_proto_ratelimiter_proto_init() {
	if File_api_proto_ratelimiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ratelimiter_proto_rawDesc), len(file_api_proto_ratelimiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ratelimiter_proto_goTypes,
		DependencyIndexes: file_api_proto_ratelimiter_proto_depIdxs,
		MessageInfos:      file_api_proto_ratelimiter_proto_msgTypes,
	}.Build()
	File_api_proto_ratelimiter_proto = out.File
	file_api_proto_ratelimiter_proto_goTypes = nil
	file_api_proto_ratelimiter_proto_depIdxs = nil
}
